version: '3.4'

services:
  flowerss:
    build:
      context: .
      dockerfile: Dockerfile
    image: flowerss
    volumes:
      - ./config.yml:/flowerss/config.yml
      - ./data/sqlite/data.db:/flowerss/data/sqlite/data.db
    restart: unless-stopped
    depends_on:
      - nsqlookupd
      - nsqd
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data
    depends_on:
      - nsqlookupd
    volumes:
      - ./data/nsq:/data
    ports:
      - "4150:4150"
      - "4151:4151"
